### PR TITLE
Fix background-color

### PR DESCRIPTION
**Pull request by GitHyppa**
Hello man! dont worry! i fixed your problem! enjoy! :) #4

### CODE REVIEW

**Comment by joacimnilsson** [comment]
Can you link the pr with the issue

**Comment by joacimnilsson** [comment]
But I want it to be in a separate css file so we can add more styling later

**Comment by GitHyppa** [comment]
okey, i fix!

**Review by joacimnilsson — APPROVED** [review]
Looks good! GJ!

**Pull request merged**
